package org.guestbook.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.guestbook.domain.Guest;
import org.guestbook.domain.GuestExample;

public interface GuestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    int countByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    int deleteByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    int deleteByPrimaryKey(String guestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    int insert(Guest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    int insertSelective(Guest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    List<Guest> selectByExampleWithRowbounds(GuestExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    List<Guest> selectByExample(GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    Guest selectByPrimaryKey(String guestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    int updateByExampleSelective(@Param("record") Guest record, @Param("example") GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    int updateByExample(@Param("record") Guest record, @Param("example") GuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    int updateByPrimaryKeySelective(Guest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guests
     *
     * @mbggenerated Mon Aug 20 14:43:53 ICT 2018
     */
    int updateByPrimaryKey(Guest record);
}